function score = segment_grading(r)
r.ints_face = r.ints_face/r.face_area;
r.ints_mouth = r.ints_mouth/r.mouth_area;
r.areas = r.areas/prod(r.winSize);
ints_not = r.ints_not./r.areas;

must_have = r.ints_face > 0;
must_have = must_have & (r.ints_mouth > 0);
must_have = must_have & ((r.bboxes(:,3)- r.bboxes(:,1)) < .8)';
must_have = must_have & ints_not > 0;
score =  -r.ints_face...
    +(r.ints_mouth)... % occlude much of mouth
    +1*(r.ints_face<0.5)+...  % occlude face only partially    
    ((r.bboxes(:,4)- r.bboxes(:,2)) < .7)'+...
    (r.bboxes(:,2)' > 0.3)+...
    (r.ucmStrengths>0)+0*(0*r.ucmStrengths) + ...
    0*(r.ucmStrengths_noface) + ...    
    (r.ints_not>10)+0*(r.areas<.7) + ...
    (r.areas<.5)+...
    0*r.gradientStrengths+...
    0*r.gradientStrengths_noface+...    
    r.gpbStrengths + ...
    r.gpbStrengths_noface;
        
score(~must_have) = false;
score(isnan(score)) = -1;